name: Generate Caves

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Generate Caves
      run: |
        cd fest_joiner
        cargo run
        mkdir artifacts/
        cp ../caves/CAVENEW.ZZT artifacts/
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifacts
        path: artifacts/
